<?php
// sitemap.php - Dynamic Sitemap Gateway for World of Shelves
ob_start();

define('ALLOW_SITEMAP_GEN', true);
require_once __DIR__ . '/config/init.php';

// Clear any accidental whitespace or output generated by bootstrap files
ob_clean();

header('Content-Type: application/xml; charset=utf-8');
header('Cache-Control: public, max-age=3600, must-revalidate');

$site_url = defined('CANONICAL_PROD_URL') ? CANONICAL_PROD_URL : 'https://worldofshelves.com';

echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">' . "\n";

/**
 * Safely resolves lastmod timestamp from a record without fabricating fake dates.
 */
function resolve_sitemap_lastmod($row, array $fields) {
    foreach ($fields as $f) {
        if (!empty($row[$f])) {
            $val = trim($row[$f]);
            if ($val !== '' && $val !== '0000-00-00 00:00:00' && $val !== '0000-00-00') {
                $time = strtotime($val);
                if ($time > 0) {
                    return date('Y-m-d', $time);
                }
            }
        }
    }
    return null;
}

/**
 * Helper to output a sitemap URL block with alternates.
 */
function output_sitemap_url($ar_url, $en_url, $lastmod, $changefreq, $priority) {
    echo '  <url>' . "\n";
    echo '    <loc>' . htmlspecialchars($ar_url, ENT_XML1, 'UTF-8') . '</loc>' . "\n";
    echo '    <xhtml:link rel="alternate" hreflang="ar" href="' . htmlspecialchars($ar_url, ENT_XML1, 'UTF-8') . '"/>' . "\n";
    echo '    <xhtml:link rel="alternate" hreflang="en" href="' . htmlspecialchars($en_url, ENT_XML1, 'UTF-8') . '"/>' . "\n";
    echo '    <xhtml:link rel="alternate" hreflang="x-default" href="' . htmlspecialchars($ar_url, ENT_XML1, 'UTF-8') . '"/>' . "\n";
    if ($lastmod !== null) {
        echo '    <lastmod>' . $lastmod . '</lastmod>' . "\n";
    }
    echo '    <changefreq>' . $changefreq . '</changefreq>' . "\n";
    echo '    <priority>' . $priority . '</priority>' . "\n";
    echo '  </url>' . "\n";
}

// 1. Core Static Pages (No fabricated lastmod)
$static_pages = [
    '' => ['priority' => '1.0', 'changefreq' => 'daily'],
    'about' => ['priority' => '0.8', 'changefreq' => 'weekly'],
    'products' => ['priority' => '0.9', 'changefreq' => 'daily'],
    'services' => ['priority' => '0.8', 'changefreq' => 'weekly'],
    'projects' => ['priority' => '0.8', 'changefreq' => 'weekly'],
    'used-shelves' => ['priority' => '0.8', 'changefreq' => 'weekly'],
    'installation' => ['priority' => '0.8', 'changefreq' => 'weekly'],
    'contact' => ['priority' => '0.7', 'changefreq' => 'monthly']
];

foreach ($static_pages as $page => $meta) {
    $path = ($page === '') ? '' : '/' . $page;
    $ar_url = $site_url . $path;
    $en_url = $site_url . $path . '?lang=en';
    output_sitemap_url($ar_url, $en_url, null, $meta['changefreq'], $meta['priority']);
}

// 2. Active Products
try {
    $stmt = $pdo->query("SELECT slug, created_at, updated_at FROM products WHERE is_active = 1");
    while ($p = $stmt->fetch(PDO::FETCH_ASSOC)) {
        if (empty($p['slug'])) continue;
        $ar_url = $site_url . '/products/' . $p['slug'];
        $en_url = $site_url . '/products/' . $p['slug'] . '?lang=en';
        $lastmod = resolve_sitemap_lastmod($p, ['updated_at', 'created_at']);
        output_sitemap_url($ar_url, $en_url, $lastmod, 'weekly', '0.8');
    }
} catch (Exception $e) {
    error_log("Sitemap product fetch error: " . $e->getMessage());
}

// 3. Active Projects
try {
    $stmt = $pdo->query("SELECT slug, created_at, updated_at, project_date FROM projects WHERE is_active = 1");
    while ($p = $stmt->fetch(PDO::FETCH_ASSOC)) {
        if (empty($p['slug'])) continue;
        $ar_url = $site_url . '/project-details?project=' . $p['slug'];
        $en_url = $site_url . '/project-details?project=' . $p['slug'] . '&lang=en';
        $lastmod = resolve_sitemap_lastmod($p, ['updated_at', 'created_at', 'project_date']);
        output_sitemap_url($ar_url, $en_url, $lastmod, 'weekly', '0.7');
    }
} catch (Exception $e) {
    error_log("Sitemap project fetch error: " . $e->getMessage());
}

// 4. Product Categories
try {
    $stmt = $pdo->query("SELECT slug, created_at, updated_at FROM categories");
    while ($c = $stmt->fetch(PDO::FETCH_ASSOC)) {
        if (empty($c['slug'])) continue;
        $ar_url = $site_url . '/products/category/' . $c['slug'];
        $en_url = $site_url . '/products/category/' . $c['slug'] . '?lang=en';
        $lastmod = resolve_sitemap_lastmod($c, ['updated_at', 'created_at']);
        output_sitemap_url($ar_url, $en_url, $lastmod, 'weekly', '0.7');
    }
} catch (Exception $e) {
    error_log("Sitemap product categories fetch error: " . $e->getMessage());
}

// 5. Project Categories
try {
    $stmt = $pdo->query("SELECT slug, created_at, updated_at FROM project_categories WHERE is_active = 1");
    while ($c = $stmt->fetch(PDO::FETCH_ASSOC)) {
        if (empty($c['slug'])) continue;
        $ar_url = $site_url . '/projects/category/' . $c['slug'];
        $en_url = $site_url . '/projects/category/' . $c['slug'] . '?lang=en';
        $lastmod = resolve_sitemap_lastmod($c, ['updated_at', 'created_at']);
        output_sitemap_url($ar_url, $en_url, $lastmod, 'weekly', '0.6');
    }
} catch (Exception $e) {
    error_log("Sitemap project categories fetch error: " . $e->getMessage());
}

echo '</urlset>';
ob_end_flush();
